import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api, type AnalyticsResponse, type QueryResult } from '../api';
import { Markdown, Spinner, fmtDateFull } from '../components/ui';
import { DataChart, DataTable, applicableChartTypes } from '../components/charts';

export default function SharedReport() {
  const { id = '' } = useParams();
  const { data: conv, isLoading, isError } = useQuery({
    queryKey: ['shared', id],
    queryFn: () => api.getShared(id),
    retry: false,
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <Spinner className="h-6 w-6" />
      </div>
    );
  }

  if (isError || !conv) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6">
        <div className="text-center">
          <div className="text-3xl mb-3">🔗</div>
          <p className="text-sm text-gray-300">This shared report doesn't exist or has expired.</p>
          <p className="text-xs text-gray-600 mt-1">Ask the person who shared it to generate a new link.</p>
        </div>
      </div>
    );
  }

  const insights = conv.messages.filter((m) => m.role === 'assistant' && m.response && !m.response.error);

  return (
    <div className="min-h-screen bg-gray-950">
      <div className="max-w-4xl mx-auto p-6 space-y-6">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 border-b border-gray-800 pb-4">
          <div className="flex items-center gap-3">
            <img src="https://hobbiton.tech/assets/logo2-7db998ca.png" alt="Hobbiton" className="h-8 w-8 rounded object-contain" />
            <div>
              <div className="text-[10px] font-bold uppercase tracking-widest text-gray-500">Sentinel · Shared report</div>
              <h1 className="text-lg font-semibold text-white leading-tight">{conv.title}</h1>
              <div className="text-xs text-gray-600 mt-0.5">
                {fmtDateFull(conv.updatedAt)} · {conv.database}
              </div>
            </div>
          </div>
          <button
            onClick={() => window.print()}
            className="px-3 py-1.5 text-xs border border-gray-800 rounded text-gray-400 hover:text-gray-200 hover:bg-gray-900 transition-colors print:hidden shrink-0"
          >
            Print / Save PDF
          </button>
        </div>

        {insights.length === 0 && (
          <div className="text-center py-16">
            <div className="text-3xl mb-3">📊</div>
            <p className="text-sm text-gray-400">No insights in this report yet.</p>
          </div>
        )}

        {insights.map((m, i) => (
          <InsightBlock key={i} response={m.response!} prompt={findPrompt(conv.messages, m)} index={i} />
        ))}

        <div className="border-t border-gray-800 pt-4 text-center text-[10px] text-gray-700">
          Generated by Sentinel Analytics · Hobbiton
        </div>
      </div>
    </div>
  );
}

function findPrompt(messages: { role: string; content: string }[], target: unknown): string | null {
  const idx = messages.indexOf(target as (typeof messages)[number]);
  for (let i = idx - 1; i >= 0; i--) {
    if (messages[i].role === 'user') return messages[i].content;
  }
  return null;
}

function InsightBlock({ response: r, prompt, index }: { response: AnalyticsResponse; prompt: string | null; index: number }) {
  const results: QueryResult[] =
    (r.results ?? []).filter((q) => q.rows.length > 0).length > 0
      ? r.results.filter((q) => q.rows.length > 0)
      : r.rows?.length > 0
        ? [{ label: null, sql: r.sql, chartType: r.chartType, columns: r.columns, rows: r.rows, rowCount: r.rowCount }]
        : [];

  return (
    <div className="border border-gray-800 rounded-xl p-5 bg-gray-900/30 space-y-4 break-inside-avoid">
      {prompt && (
        <div className="text-xs text-gray-500 italic border-l-2 border-gray-800 pl-3">
          “{prompt}”
        </div>
      )}

      {r.explanation && <Markdown text={r.explanation} />}

      {(r.summary || r.riskLevel || r.findings?.length > 0 || r.recommendedActions?.length > 0) && (
        <div className="border border-gray-800 rounded-lg p-3 bg-gray-900/40 space-y-2">
          {r.summary && <Markdown text={r.summary} className="text-gray-200" />}
          {r.findings?.length > 0 && (
            <div>
              <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Findings</div>
              {r.findings.map((fi, fIdx) => (
                <div key={fIdx} className="text-xs text-gray-300">• {fi}</div>
              ))}
            </div>
          )}
          {r.recommendedActions?.length > 0 && (
            <div>
              <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Recommended Actions</div>
              {r.recommendedActions.map((a, aIdx) => (
                <div key={aIdx} className="text-xs text-gray-300">• {a}</div>
              ))}
            </div>
          )}
        </div>
      )}

      {results.map((qr, ri) => {
        const types = applicableChartTypes(qr.columns, qr.rows);
        const chartType = qr.chartType !== 'none' && types.includes(qr.chartType) ? qr.chartType : types[0];
        return (
          <div key={`${index}-${ri}`} className="border border-gray-800/60 rounded-lg overflow-hidden bg-gray-950/30">
            <div className="px-3 py-2 border-b border-gray-800/60 flex items-center justify-between">
              <span className="text-xs font-medium text-gray-300">{qr.label || 'Result'}</span>
              <span className="text-[10px] text-gray-600">{qr.rowCount} rows</span>
            </div>
            <div className="p-3">
              {chartType && chartType !== 'table' ? (
                <DataChart chartType={chartType} columns={qr.columns} rows={qr.rows} height={280} />
              ) : (
                <DataTable columns={qr.columns} rows={qr.rows} maxRows={25} />
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
