import { useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api, type AnalyticsResponse, type QueryResult } from '../api';
import { Markdown, fmtDateFull } from '../components/ui';
import { DataChart, DataTable, applicableChartTypes } from '../components/charts';

export default function SharedReport() {
  const { id = '' } = useParams();
  const { data: conv, isLoading, isError } = useQuery({
    queryKey: ['shared', id],
    queryFn: () => api.getShared(id),
    retry: false,
  });

  // give a saved PDF a sensible filename instead of the generic app title
  useEffect(() => {
    if (!conv) return;
    const prev = document.title;
    document.title = conv.title || 'Sentinel report';
    return () => { document.title = prev; };
  }, [conv]);

  // charts size themselves off the screen layout on mount; force a resize so
  // ApexCharts re-measures against the print layout instead of rendering blank
  useEffect(() => {
    const onBeforePrint = () => window.dispatchEvent(new Event('resize'));
    window.addEventListener('beforeprint', onBeforePrint);
    return () => window.removeEventListener('beforeprint', onBeforePrint);
  }, []);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <div className="radar h-14 w-14 opacity-70" />
      </div>
    );
  }

  if (isError || !conv) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center p-6 relative">
        <div className="atmosphere" aria-hidden />
        <div className="panel relative z-10 p-10 text-center rise">
          <div className="radar h-14 w-14 mx-auto mb-4 opacity-80" aria-hidden />
          <p className="font-display text-sm text-gray-300">This shared report doesn't exist or has expired.</p>
          <p className="text-xs text-gray-600 mt-1.5">Ask the person who shared it to generate a new link.</p>
        </div>
      </div>
    );
  }

  const insights = conv.messages.filter((m) => m.role === 'assistant' && m.response && !m.response.error);

  return (
    <div className="min-h-screen bg-gray-950 relative">
      <div className="atmosphere" aria-hidden />
      <div className="max-w-4xl mx-auto p-6 space-y-5 relative z-10" data-stagger>
        {/* Header */}
        <div className="flex items-start justify-between gap-4 border-b border-gray-800 pb-4">
          <div className="flex items-center gap-3">
            <img src="https://hobbiton.tech/assets/logo2-7db998ca.png" alt="Hobbiton" className="h-8 w-8 rounded object-contain" />
            <div>
              <div className="kicker">Sentinel · Shared report</div>
              <h1 className="font-display text-lg font-semibold text-white leading-tight mt-0.5">{conv.title}</h1>
              <div className="font-mono text-[11px] text-gray-600 mt-1">
                {fmtDateFull(conv.updatedAt)} · {conv.database}
              </div>
            </div>
          </div>
          <button
            onClick={() => window.print()}
            className="px-3 py-1.5 text-xs border border-gray-700/80 rounded-md text-gray-400 hover:text-gray-200 hover:bg-gray-900 transition-colors print:hidden shrink-0"
          >
            Print
          </button>
        </div>

        {insights.length === 0 && (
          <div className="panel p-12 text-center">
            <div className="radar h-14 w-14 mx-auto mb-4 opacity-80" aria-hidden />
            <p className="font-display text-sm text-gray-400">No insights in this report yet.</p>
          </div>
        )}

        {insights.map((m, i) => (
          <InsightBlock key={i} response={m.response!} prompt={findPrompt(conv.messages, m)} index={i} />
        ))}

        <div className="border-t border-gray-800 pt-4 text-center font-mono text-[10px] text-gray-700 uppercase tracking-wider">
          Generated by Sentinel Analytics · Hobbiton
        </div>
      </div>
    </div>
  );
}

function findPrompt(messages: { role: string; content: string }[], target: unknown): string | null {
  const idx = messages.indexOf(target as (typeof messages)[number]);
  for (let i = idx - 1; i >= 0; i--) {
    if (messages[i].role === 'user') return messages[i].content;
  }
  return null;
}

function InsightBlock({ response: r, prompt, index }: { response: AnalyticsResponse; prompt: string | null; index: number }) {
  const results: QueryResult[] =
    (r.results ?? []).filter((q) => q.rows.length > 0).length > 0
      ? r.results.filter((q) => q.rows.length > 0)
      : r.rows?.length > 0
        ? [{ label: null, sql: r.sql, chartType: r.chartType, columns: r.columns, rows: r.rows, rowCount: r.rowCount }]
        : [];

  return (
    <div className="panel p-5 space-y-4 border-l-2 border-l-emerald-500/40">
      {prompt && (
        <div className="text-xs text-gray-500 italic border-l-2 border-emerald-500/25 pl-3 break-inside-avoid">
          “{prompt}”
        </div>
      )}

      {r.explanation && <Markdown text={r.explanation} />}

      {(r.summary || r.riskLevel || r.findings?.length > 0 || r.recommendedActions?.length > 0) && (
        <div className="border border-gray-800 rounded-lg p-3 bg-gray-950/50 space-y-2.5 break-inside-avoid">
          {r.summary && <Markdown text={r.summary} className="text-gray-200" />}
          {r.findings?.length > 0 && (
            <div>
              <div className="kicker mb-1.5">Findings</div>
              {r.findings.map((fi, fIdx) => (
                <div key={fIdx} className="text-xs text-gray-300 flex gap-2 py-0.5">
                  <span className="text-emerald-500/70 shrink-0">▸</span>
                  <span>{fi}</span>
                </div>
              ))}
            </div>
          )}
          {r.recommendedActions?.length > 0 && (
            <div>
              <div className="kicker mb-1.5">Recommended Actions</div>
              {r.recommendedActions.map((a, aIdx) => (
                <div key={aIdx} className="text-xs text-gray-300 flex gap-2 py-0.5">
                  <span className="text-amber-500/70 shrink-0">▸</span>
                  <span>{a}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {results.map((qr, ri) => {
        const types = applicableChartTypes(qr.columns, qr.rows);
        const chartType = qr.chartType !== 'none' && types.includes(qr.chartType) ? qr.chartType : types[0];
        return (
          <div key={`${index}-${ri}`} className="border border-gray-800/60 rounded-lg overflow-hidden bg-gray-950/40 break-inside-avoid">
            <div className="px-3 py-2 border-b border-gray-800/60 flex items-center justify-between">
              <span className="font-display text-xs font-medium text-gray-300">{qr.label || 'Result'}</span>
              <span className="font-mono text-[10px] text-gray-600 tnum">{qr.rowCount} rows</span>
            </div>
            <div className="p-3">
              {chartType && chartType !== 'table' ? (
                <DataChart chartType={chartType} columns={qr.columns} rows={qr.rows} height={280} />
              ) : (
                <DataTable columns={qr.columns} rows={qr.rows} maxRows={25} />
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
