// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentinel.Admin.Data;

#nullable disable

namespace Sentinel.Admin.Data.Migrations
{
    [DbContext(typeof(SentinelClickHouseContext))]
    partial class SentinelClickHouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Sentinel.Admin.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("ip_address");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DateTime")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "id" });
                });

            modelBuilder.Entity("Sentinel.Admin.Models.EvidenceSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("created_by");

                    b.Property<bool>("Enabled")
                        .HasColumnType("Bool")
                        .HasColumnName("enabled");

                    b.Property<string>("EvidenceChecks")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("evidence_checks");

                    b.Property<string>("EvidenceDatabase")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("evidence_database");

                    b.Property<string>("JoinMappings")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("join_mappings");

                    b.Property<string>("LipilaMerchantIds")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("lipila_merchant_ids");

                    b.Property<int>("LipilaPartnerId")
                        .HasColumnType("Int32")
                        .HasColumnName("lipila_partner_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("notes");

                    b.Property<string>("TableDescriptions")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("table_descriptions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("String")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.ToTable("evidence_sources", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "id" });
                });

            modelBuilder.Entity("Sentinel.Admin.Models.FraudPatternEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int32")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("Bool")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("String")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.ToTable("fraud_patterns", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "id" });
                });

            modelBuilder.Entity("Sentinel.Admin.Models.RunLog", b =>
                {
                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("args");

                    b.Property<uint>("DurationMs")
                        .HasColumnType("UInt32")
                        .HasColumnName("duration_ms");

                    b.Property<ushort>("Iteration")
                        .HasColumnType("UInt16")
                        .HasColumnName("iteration");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("result");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("run_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("started_at");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("tool_name");

                    b.ToTable("run_logs", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "tuple()" });
                });

            modelBuilder.Entity("Sentinel.Admin.Models.RunSummary", b =>
                {
                    b.Property<ushort>("AlertsSent")
                        .HasColumnType("UInt16")
                        .HasColumnName("alerts_sent");

                    b.Property<ushort>("CasesCreated")
                        .HasColumnType("UInt16")
                        .HasColumnName("cases_created");

                    b.Property<ushort>("CasesResolved")
                        .HasColumnType("UInt16")
                        .HasColumnName("cases_resolved");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("finished_at");

                    b.Property<uint>("InputTokens")
                        .HasColumnType("UInt32")
                        .HasColumnName("input_tokens");

                    b.Property<ushort>("Iterations")
                        .HasColumnType("UInt16")
                        .HasColumnName("iterations");

                    b.Property<uint>("OutputTokens")
                        .HasColumnType("UInt32")
                        .HasColumnName("output_tokens");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("run_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("triggered_by");

                    b.ToTable("run_summaries", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "tuple()" });
                });

            modelBuilder.Entity("Sentinel.Admin.Models.WorkflowDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("String")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("cron_expression");

                    b.Property<string>("CustomPrompt")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("custom_prompt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("description");

                    b.Property<string>("EmailRecipients")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("email_recipients");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("email_subject");

                    b.Property<bool>("Enabled")
                        .HasColumnType("Bool")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("Bool")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("system_prompt");

                    b.Property<string>("TargetDatabase")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("target_database");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("workflows", (string)null);

                    b
                        .HasAnnotation("ClickHouse:Engine", "MergeTree")
                        .HasAnnotation("ClickHouse:OrderBy", new[] { "id" });
                });
#pragma warning restore 612, 618
        }
    }
}
